# array() function

In [1]:
import numpy as np
l=[[10,20,30],[40,50,60]]
a=np.array(l)
print(a)

[[10 20 30]
 [40 50 60]]


In [4]:
t=(10,20,30,40,50)
a=np.array(t)
print(a)

[10 20 30 40 50]


In [5]:
t=('disha','ram','shyam')
a=np.array(t)
print(a)

['disha' 'ram' 'shyam']


In [6]:
t=('disha','ram','shyam',30,40,50)
a=np.array(t)
print(a)

['disha' 'ram' 'shyam' '30' '40' '50']


# upcasting

In [7]:
a=np.array([90,999,888])
print(a.dtype)

int32


In [8]:
a=np.array([90,999,888])
print(a)
print(type(a))
print(a.dtype)

[ 90 999 888]
<class 'numpy.ndarray'>
int32


In [9]:
a=np.array([90,999,888,65.76])
print(a)
print(a.dtype)

[ 90.   999.   888.    65.76]
float64


In [10]:
a=np.array([90,999,888],dtype=float)
print(a)

[ 90. 999. 888.]


In [11]:
a=np.array([90,999,888],dtype=complex)
print(a)

[ 90.+0.j 999.+0.j 888.+0.j]


In [13]:
a=np.array([90,999,888,0],dtype=bool)
print(a)

[ True  True  True False]


In [14]:
a=np.array(True+True,dtype=str)
print(a)

2


In [15]:
a=np.array(str(True+True)+'Hello')
print(a)

2Hello


In [16]:
a=np.array([90,999,888,65.76],dtype=int)
print(a)
print(a.dtype)

[ 90 999 888  65]
int32


In [17]:
a=np.array([90,999,888,65.76,'Hello',True,False,4.5,67])
print(a)
print(a.dtype)

['90' '999' '888' '65.76' 'Hello' 'True' 'False' '4.5' '67']
<U32


In [18]:
a=np.array([90,999,888,65.76,'Hello',True,False,4.5,67],dtype=object)
print(a)
print(a.dtype)

[90 999 888 65.76 'Hello' True False 4.5 67]
object


# arange() function

In [19]:
a=np.arange(10,50,1)
print(a)
print(a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int32


In [20]:
a=np.arange(10,50)
print(a)
print(a.dtype)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
int32


In [24]:
a=np.arange(0,)
print(a)
print(a.dtype)

[]
int32


In [25]:
a=np.arange(0,1)
print(a)
print(a.dtype)

[0]
int32


In [26]:
a=np.arange(0,20,2)
print(a)
print(a.dtype)

[ 0  2  4  6  8 10 12 14 16 18]
int32


# linspace() function

In [28]:
a=np.linspace(0,100)
print(a)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [29]:
a=np.linspace(0,100,num=5)
print(a)

[  0.  25.  50.  75. 100.]


In [30]:
a=np.linspace(0,20,2)
b=np.arange(0,20,2)
print(a)
print(b)

[ 0. 20.]
[ 0  2  4  6  8 10 12 14 16 18]


In [41]:
a=np.linspace(0,100,num=5,endpoint=False,retstep=False,dtype=int)
print(a)

[ 0 20 40 60 80]


In [42]:
a=np.linspace(0,100,num=5,endpoint=True,retstep=True,dtype=int)
print(a)

(array([  0,  25,  50,  75, 100]), 25.0)


In [44]:
print(help(np.linspace))

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

# zeros() function

In [48]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
a=np.zeros((10,10),dtype=int)
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [52]:
a=np.zeros((5,20),dtype=int)
print(a)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


# multidimentional array

In [57]:
a=np.zeros((1,2,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]]


# ones() function

In [61]:
a=np.ones((2,4,8))
print(a)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [62]:
a=(2,4,8)
np.ones(a)

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

# full() function

In [75]:
a=np.full((10),np.inf)
print(a)

[inf inf inf inf inf inf inf inf inf inf]


In [65]:
a=np.full((2,4,6),500)
print(a)

[[[500 500 500 500 500 500]
  [500 500 500 500 500 500]
  [500 500 500 500 500 500]
  [500 500 500 500 500 500]]

 [[500 500 500 500 500 500]
  [500 500 500 500 500 500]
  [500 500 500 500 500 500]
  [500 500 500 500 500 500]]]


# eye() function

In [67]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
a=np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [69]:
a=np.eye(4,5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [70]:
a=np.eye(4,4,-1)
print(a)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [81]:
a=np.eye(4,4,2)
print(a)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [77]:
a=np.eye(4,4,-6)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# identity() function

In [78]:
a=np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [84]:
a=np.identity(2,dtype=int)
print(a)

[[1 0]
 [0 1]]


# empty() function

In [95]:
a=np.empty([2,3],dtype=int)
print(a)

[[         0 1072693248          0]
 [1072693248          0 1072693248]]


In [90]:
a=np.empty((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [93]:
print(help(np.empty))

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

# random()

# rand()

In [4]:
a=np.random.rand()
print(a)

0.28233016975763947


In [7]:
a=np.random.rand(4,3)
print(a)

[[0.26621992 0.45147425 0.44812907]
 [0.16767491 0.87614643 0.06492461]
 [0.34755666 0.39923523 0.19385354]
 [0.47332424 0.16838938 0.17064115]]


In [9]:
a=np.random.rand(3,4,5)
print(a)

[[[0.67080016 0.41252012 0.87020667 0.1749133  0.13360204]
  [0.08751889 0.13612126 0.38512153 0.94421541 0.36078866]
  [0.4020606  0.25973622 0.76095458 0.30721314 0.6780791 ]
  [0.87019732 0.60389826 0.07432162 0.97920638 0.52699398]]

 [[0.12900498 0.7617392  0.98074837 0.25318084 0.15871441]
  [0.68495598 0.26316869 0.41946809 0.24968225 0.54209511]
  [0.27910133 0.15839769 0.89563648 0.09899789 0.35334227]
  [0.19941347 0.65646449 0.76551508 0.54362099 0.14373333]]

 [[0.62184145 0.71560642 0.35921251 0.69156477 0.46465763]
  [0.70516581 0.87024094 0.1894219  0.14405421 0.29764851]
  [0.46460188 0.3177027  0.99147974 0.77421317 0.90881247]
  [0.32817012 0.95274392 0.19410195 0.73400021 0.62924854]]]


# uniform()

In [12]:
print(np.random.uniform())

0.7986499936501184


In [14]:
print(np.random.uniform(10,30))

21.802003460587613


In [15]:
print(np.random.uniform(15,25,size=1000))

[16.50395628 25.04587105 27.4362807  22.43625164 10.63257753 13.8572695
 23.9094331  10.70059228 16.26182122 29.72605895 29.87300207 12.18749975
 11.30994401 16.85950855 14.6085363  16.58621479 12.41177117 14.18997775
 16.47227749 22.97796043 11.9333765  18.2147902  13.16931596 12.79398535
 19.00560363 23.8140475  13.01984929 28.0668505  28.14074065 12.7946595
 24.37021808 12.94175687 22.55686254 14.52478089 14.31477256 17.41919092
 11.14415661 18.13151001 21.71649983 11.09204338 15.79106165 11.61048063
 12.87593509 27.25064807 26.77197085 20.50338061 26.75365012 25.77464132
 22.78439157 28.03441334 26.93353599 21.86419518 22.55119419 18.89887285
 28.62071311 22.08886406 23.82409946 29.87514741 11.91483014 23.41229865
 23.38293697 25.47467845 28.82681273 13.8943015  25.42024154 29.47286447
 27.49703378 26.61397064 27.74931351 19.95860898 16.4838417  18.91743477
 16.05686778 27.06317985 24.40930813 12.9519796  21.18591537 23.41523518
 23.06247707 15.85376844 11.76381499 12.27088684 29.5

In [16]:
print(np.random.uniform(15,25,size=(2,3)))

[[20.60209714 17.59184543 19.23899069]
 [22.07459737 15.81614588 22.7132404 ]]


In [17]:
print(np.random.uniform(15,25,size=(2,3,3)))

[[[15.03306013 16.24966843 19.41845657]
  [16.53114964 22.80816921 21.99527348]
  [19.47379006 19.35954938 15.0185244 ]]

 [[21.3085981  18.98942078 24.50633174]
  [19.65288041 23.90241738 15.71728975]
  [20.0011587  24.77947306 15.79101362]]]


# randn()

In [20]:
a=np.random.randn()
print(a)

-0.23053696209807625


In [21]:
a=np.random.randn(10)
print(a)

[ 0.20645411  2.40408528 -1.84599184  0.05621084  1.81668691 -1.16489496
  0.34921166  1.27083728  0.57153898 -0.92976717]


In [22]:
a=np.random.randn(4,2)
print(a)

[[ 0.58385107 -0.50868689]
 [-0.66909576 -1.06577931]
 [ 0.23408481 -1.1436608 ]
 [-2.58451527 -0.82269241]]


In [23]:
a=np.random.randn(3,4,2)
print(a)

[[[ 1.17108107e+00  5.22994973e-01]
  [ 1.69845859e+00  2.47221719e-01]
  [-5.14735293e-01 -1.13866889e+00]
  [ 1.36394893e-01  8.65323528e-01]]

 [[-1.00750280e+00  8.10150878e-01]
  [ 3.47741946e-02 -2.44580850e-01]
  [-3.51795487e-01  1.21592698e+00]
  [ 5.72758624e-01 -4.63349666e-01]]

 [[-4.77581641e-01  4.22495067e-01]
  [ 2.13481164e+00 -1.22018274e+00]
  [-1.63308364e+00  3.44178712e-01]
  [ 7.46597732e-04 -1.70058717e-01]]]


# normal()

In [28]:
a=np.random.normal(10)
print(a)

9.977883937129603


In [31]:
a=np.random.normal(10,4)
print(a)

10.252354909440184


In [34]:
a=np.random.normal(10,4,size=10000)
print(a)

[ 5.78053249  1.59125906  8.44799859 ...  5.87624392 10.03006464
  9.95686137]


# shuffle()

In [35]:
a=np.arange(15)
np.random.shuffle(a)
print(a)

[ 3 14 13  5  4 11 12 10  8  0  6  1  2  7  9]


In [36]:
a=np.randint(1,50,size=(5,5))
print(a)
np.random.shuffle(a)
print(a)

AttributeError: module 'numpy' has no attribute 'randint'